import type { FieldDefinition } from "@/types/cdc";

export const FIELD_DEFINITIONS: FieldDefinition[] = [
  {
    fieldName: "ID",
    displayName: "Listing ID",
    description: "Unique identifier for the listing.",
    category: "Listing Information",
    dataType: "string",
  },
  {
    fieldName: "TITLE",
    displayName: "Title",
    description: "The listing title shown to users.",
    category: "Listing Information",
    dataType: "string",
  },
  {
    fieldName: "DESCRIPTION",
    displayName: "Description",
    description: "The listing description text.",
    category: "Listing Information",
    dataType: "string",
  },
  {
    fieldName: "DISPLAY_NAME",
    displayName: "Display Name",
    description: "Display name associated with the listing or member.",
    category: "Listing Information",
    dataType: "string",
  },
  {
    fieldName: "PRICE",
    displayName: "Price",
    description: "Listed price amount.",
    category: "Listing Information",
    dataType: "currency",
    formatter: "price",
  },
  {
    fieldName: "BASE_PRICE",
    displayName: "Base Price",
    description: "Base price before adjustments.",
    category: "Listing Information",
    dataType: "currency",
    formatter: "price",
  },
  {
    fieldName: "PRICE_CURRENCY",
    displayName: "Currency",
    description: "Currency code for the listing price.",
    category: "Listing Information",
    dataType: "string",
  },
  {
    fieldName: "HAS_PRICE",
    displayName: "Price available",
    description: "Shows whether the listing has a price.",
    category: "Listing Information",
    dataType: "boolean",
    formatter: "yesNo",
  },
  {
    fieldName: "CATEGORIES_ID",
    displayName: "Category ID",
    description: "Category identifier for the listing.",
    category: "Listing Information",
    dataType: "string",
  },
  {
    fieldName: "NEW_CAT_ID",
    displayName: "New Category ID",
    description: "Updated category identifier if remapped.",
    category: "Listing Information",
    dataType: "string",
  },
  {
    fieldName: "CITIES_ID",
    displayName: "City ID",
    description: "City identifier for the listing location.",
    category: "Listing Information",
    dataType: "string",
  },
  {
    fieldName: "COUNTRIES_ID",
    displayName: "Country ID",
    description: "Country identifier for the listing.",
    category: "Listing Information",
    dataType: "string",
  },
  {
    fieldName: "LANG",
    displayName: "Language",
    description: "Language of the listing content.",
    category: "Listing Information",
    dataType: "language",
    formatter: "language",
  },
  {
    fieldName: "GEO_LAT",
    displayName: "Latitude",
    description: "Geographic latitude of the listing.",
    category: "Listing Information",
    dataType: "number",
  },
  {
    fieldName: "GEO_LNG",
    displayName: "Longitude",
    description: "Geographic longitude of the listing.",
    category: "Listing Information",
    dataType: "number",
  },
  {
    fieldName: "ACTIVE",
    displayName: "Active",
    description: "Shows whether the listing is currently active.",
    category: "Listing Status",
    dataType: "boolean",
    formatter: "yesNo",
  },
  {
    fieldName: "STATUS",
    displayName: "Status",
    description: "Current status code or label of the listing.",
    category: "Listing Status",
    dataType: "enum",
    formatter: "status",
  },
  {
    fieldName: "IS_FEATURED",
    displayName: "Featured",
    description: "Shows whether the listing is featured.",
    category: "Listing Status",
    dataType: "boolean",
    formatter: "yesNo",
  },
  {
    fieldName: "IS_HIGHLIGHTED",
    displayName: "Highlighted",
    description: "Shows whether the listing is highlighted.",
    category: "Listing Status",
    dataType: "boolean",
    formatter: "yesNo",
  },
  {
    fieldName: "VIOLATION",
    displayName: "Violation",
    description: "Indicates whether a violation was detected.",
    category: "Listing Status",
    dataType: "boolean",
    formatter: "violation",
  },
  {
    fieldName: "IS_FIRST_LIVE",
    displayName: "First time live",
    description: "Shows whether this is the first time the listing went live.",
    category: "Listing Status",
    dataType: "boolean",
    formatter: "yesNo",
  },
  {
    fieldName: "RECORD_EXPIRATION_DATE",
    displayName: "Expiration Date",
    description: "When the listing is set to expire.",
    category: "Listing Status",
    dataType: "date",
    formatter: "datetime",
  },
  {
    fieldName: "SF_OP",
    displayName: "CDC Operation",
    description: "The type of change captured by CDC.",
    category: "CDC",
    dataType: "enum",
    formatter: "operation",
  },
  {
    fieldName: "SF_TIMESTAMP",
    displayName: "CDC Timestamp",
    description: "When the CDC event was captured.",
    category: "CDC",
    dataType: "date",
    formatter: "datetime",
  },
  {
    fieldName: "REQUEST_ID",
    displayName: "Request ID",
    description: "Identifier for the originating request.",
    category: "CDC",
    dataType: "string",
  },
  {
    fieldName: "LAST_EDIT_ACTION",
    displayName: "Last Edit Action",
    description: "Structured details about the last edit or rule-engine action.",
    category: "CDC",
    dataType: "json",
    formatter: "jsonAction",
  },
  {
    fieldName: "DATE",
    displayName: "Date",
    description: "Date associated with the record event.",
    category: "CDC",
    dataType: "date",
    formatter: "datetime",
  },
  {
    fieldName: "RECORD_INSERT_DATE",
    displayName: "Record Insert Date",
    description: "When the listing record was first inserted.",
    category: "CDC",
    dataType: "date",
    formatter: "datetime",
  },
  {
    fieldName: "RECORD_UPDATE_DATE",
    displayName: "Record Update Date",
    description: "When the listing record was last updated.",
    category: "CDC",
    dataType: "date",
    formatter: "datetime",
  },
  {
    fieldName: "MEMBERS_ID",
    displayName: "Member ID",
    description: "Identifier of the member who owns the listing.",
    category: "User Information",
    dataType: "string",
    sensitive: true,
  },
  {
    fieldName: "EMAIL",
    displayName: "Email",
    description: "Contact email associated with the listing.",
    category: "User Information",
    dataType: "string",
    sensitive: true,
    formatter: "email",
  },
  {
    fieldName: "PHONE",
    displayName: "Phone",
    description: "Contact phone number associated with the listing.",
    category: "User Information",
    dataType: "string",
    sensitive: true,
    formatter: "phone",
  },
  {
    fieldName: "POST_COUNT",
    displayName: "Post Count",
    description: "Number of posts associated with the member or listing.",
    category: "User Information",
    dataType: "number",
  },
  {
    fieldName: "NUMBER_OF_TIMES_REPOSTED",
    displayName: "Times Reposted",
    description: "How many times the listing was reposted.",
    category: "Activity",
    dataType: "number",
  },
  {
    fieldName: "POST_SOURCE",
    displayName: "Post Source",
    description: "Source channel used to create the post.",
    category: "Activity",
    dataType: "string",
  },
  {
    fieldName: "POST_TYPE",
    displayName: "Post Type",
    description: "Type of post or listing.",
    category: "Activity",
    dataType: "string",
  },
  {
    fieldName: "POST_INSERT_IP_COUNTRY",
    displayName: "Posting country",
    description: "Country derived from the IP used when the post was created.",
    category: "Technical Information",
    dataType: "country",
    formatter: "country",
  },
  {
    fieldName: "POST_UPDATE_IP_COUNTRY",
    displayName: "Update country",
    description: "Country derived from the IP used when the post was updated.",
    category: "Technical Information",
    dataType: "country",
    formatter: "country",
  },
];

export const FIELD_MAP = new Map(
  FIELD_DEFINITIONS.map((field) => [field.fieldName.toUpperCase(), field]),
);

export function getFieldDefinition(fieldName: string): FieldDefinition {
  const known = FIELD_MAP.get(fieldName.toUpperCase());
  if (known) return known;

  return {
    fieldName,
    displayName: fieldName
      .replace(/_/g, " ")
      .toLowerCase()
      .replace(/\b\w/g, (c) => c.toUpperCase()),
    description: "Technical field detected. No business definition available.",
    category: "Technical Information",
    dataType: "unknown",
  };
}

export const DEFAULT_TABLE_COLUMNS = [
  "ID",
  "TITLE",
  "SF_OP",
  "STATUS",
  "ACTIVE",
  "PRICE",
  "PRICE_CURRENCY",
  "POST_INSERT_IP_COUNTRY",
  "VIOLATION",
  "SF_TIMESTAMP",
];

export const CATEGORY_ORDER = [
  "Listing Information",
  "Listing Status",
  "CDC",
  "User Information",
  "Activity",
  "Technical Information",
];
